apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: unifiappay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fiapbank-api
  template:
    metadata:
      labels:
        app: fiapbank-api
    spec: # <-- Este Ã© o spec do POD
      
      # ------------------- VAI EXATAMENTE AQUI ------------------- #
      # (Alinhado com 'containers:' abaixo)
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000 # O ID 1000 que definimos no Dockerfile (appuser)
      # ------------------------------------------------------------- #

      containers:
      - name: api
        image: robelio/fiapbank-api:v1 
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "db-service"
        - name: DB_USER
          value: "fiap"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        resources: # <-- Este fica DENTRO de 'containers:'
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: unifiappay
spec:
  type: NodePort
  selector:
    app: fiapbank-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080