apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: unifiappay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fiapbank-api
  template:
    metadata:
      labels:
        app: fiapbank-api
    spec:
      containers:
      - name: api
        image: robelio/fiapbank-api:v1 # <-- Sua imagem do Docker Hub
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "db-service" # O nome do Service do DB
        - name: DB_USER
          value: "fiap"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        
        # ------------------- VAI EXATAMENTE AQUI ------------------- #
        # (Alinhado com 'name', 'image', 'ports', e 'env' acima)
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m" # Meio core
          requests:
            memory: "64Mi"
            cpu: "250m" # 1/4 de core
        # ------------------------------------------------------------- #

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: unifiappay
spec:
  type: NodePort # Para acessar facilmente no Kind
  selector:
    app: fiapbank-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080 # AcessÃ­vel em http://localhost:30080